spring:
  application:
    name: tongxinmall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.142.1:8848
    alicloud:
      access-key: LTAI4GJmdcKQb6BUYFTUAdRB
      secret-key: NyCebD3USRfX0TQPaVLxmGVZ3cc4Wd
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: tongxinmall

server:
  port: 30000

logging:
  level:
    com.ziyin.tongxinmall.product: debug


